# Site
title: David Freerksen
email: dfreerksen@gmail.com
description: David Freerksen is a software engineer located in Elk Grove, Calfironia. Specializing in Ruby, Rails, PHP, SQL, HTML, CSS and Javascript development.
keywords:
  - david
  - freerksen
  - witheringtree
  - ruby
  - rails
  - php

# URLs and paths
baseurl: ""
url: "http://www.davidfreerksen.com"

# Version
version: 5.0.0

# Encoding
encoding: utf-8

# Social networks
social:
  twitter: dfreerksen
  facebook: dfreerksen
  instagram: dfreerksen
  github: dfreerksen
  linkedin: david-freerksen

# Disqus comments
disqus: davidfreerksen

# Analytics
analytics:
  google: UA-59502340-1

# Site verification
verification:
  msvalidate: 8F639718B84CBE19F52EA4AC7CBA1D06

# Pagination
paginate: 10
permalink: /posts/:year/:month/:day/:title/
paginate_path: /posts/page/:num

# Default layouts
defaults:
  -
    scope:
      type: posts
    values:
      type: post
      layout: post
      article: true
      comments: true
      sharing: true
      excerpt_separator: <!--more-->
  -
    scope:
      type: pages
    values:
      type: page
      layout: page
      article: false

# CSS compression
sass:
  style: :compressed

# Plugins
gems:
  - jekyll-sitemap

# Timezone
timezone: America/Los_Angeles

# Include in build
include:
  - .htaccess

# Exclude in build
exclude:
  - Gemfile
  - README.md
  - DESIGN.md
  - HELP.md
  - TODO.md

# Markdown
markdown: kramdown
