# Site
title: David Freerksen
email: dfreerksen@gmail.com
description: David Freerksen is a software engineer located in Elk Grove, Calfironia. Specializing in Ruby, Rails, PHP, SQL, HTML, CSS and Javascript development.
keywords:
  - david
  - freerksen
  - davidfreerksen
  - dfreerksen
  - ruby
  - rails
  - node
  - javascript

# URLs and paths
baseurl: ""
url: http://www.davidfreerksen.com

# Version
version: 1.2.0 # format: major.update.fix

# Encoding
encoding: utf-8

# Social networks
social:
  twitter: dfreerksen
  facebook: dfreerksen
  instagram: dfreerksen
  github: dfreerksen
  linkedin: dfreerksen

# Available for hire
available: false

# Disqus comments
disqus: davidfreerksen

# Analytics
analytics:
  google: UA-59502340-1

# Site verification
verification:
  msvalidate: 8F639718B84CBE19F52EA4AC7CBA1D06

# Pagination
paginate: 10
permalink: /posts/:year/:month/:day/:title/
paginate_path: /page/:num

# Excerpts
# excerpt_separator: <!--more-->

# Default layouts
defaults:
  -
    scope:
      path: tag
    values:
      type: tag
      layout: tag
  -
    scope:
      type: posts
    values:
      type: post
      layout: post
      article: true
      comments: true
      sharing: true
  -
    scope:
      type: pages
    values:
      type: page
      layout: page
      article: false

# CSS compression
sass:
  # style: :expanded
  style: :compressed

# Plugins
gems:
  - jekyll-sitemap

# Timezone
timezone: America/Los_Angeles

# Include in build
include:
  - .htaccess

# Exclude in build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - TODO.md
  - bower.json
  - /bower_components
  - /gulpfile.js
  - gulpconfig.js
  - /node_modules
  - package.json
  - npm-debug.log
  - /assets/css
  - /assets/js

# Markdown
markdown: redcarpet
