# Encoding
encoding: utf-8

# Site
title: David Freerksen
email: dfreerksen@gmail.com
description: David Freerksen is a software engineer located in Elk Grove, Calfironia. Specializing in Ruby, Rails, PHP, SQL, HTML, CSS and Javascript development.
keywords: # Site keywords
  - david
  - freerksen
  - davidfreerksen
  - dfreerksen
  - ruby
  - rails
  - node
  - javascript

# URLs and paths
baseurl: "" # Base path of your site. Useful when your Jekyll site is at /blog
url: http://www.davidfreerksen.com # Base URL of your site

# Social networks
social: # Social media usernames
  twitter: dfreerksen
  facebook: dfreerksen
  instagram: dfreerksen
  github: dfreerksen
  linkedin: dfreerksen

# Disqus comments
comments:
  provider: disqus # Comments provider. Only one can be used
  disqus:
    short_name: davidfreerksen
  facebook:
    app_id:
    num_posts: 5
    width: 100%
    colorscheme: light

# Analytics
analytics: # Site analytics. Multiple can be used at the same time
  google:
    tracking_id: UA-59502340-1
  mixpanel:
    token:

# Site verification
verification: # Site verification
  google:
  msvalidate: 8F639718B84CBE19F52EA4AC7CBA1D06

# Pagination
paginate: 12 # Number of posts to display per page
permalink: /posts/:year/:month/:day/:title/ # Post URL format
paginate_path: /page/:num # Post pagination URL format

# Excerpts
# excerpt_separator: <!--more-->

# Timezone
timezone: America/Los_Angeles # Your timezone

# Default layouts
defaults:
  -
    scope:
      type: posts
    values:
      type: post
      layout: post
      article: true
      comments: true
      sharing: false
  -
    scope:
      type: pages
    values:
      type: page
      layout: page
      article: false

# CSS compression
sass:
  # style: :expanded
  style: :compressed

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-gist

# Exclude in build
exclude:
  - README.md
